language: node_js
node_js:
  - '7'
  - '6'

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    secure: JE2MzPtnWYoe65rY/phM7G3hhbTLHeVBPz/BeOoNS1J0aerDW5AW+3tbB4CC0kZ3MdUH5sKPfR3o4WgfvqzcsnDZA9KjFfc/i27ELzheB7EGdfWMg3/kiGzkNwR14Yh+mTPfRfX+4MMOQ0g7amaUiN4HHwxv5Y9QWMkCI6aC740C6m2pzzCuSsaifdELvr3iBJ8AyOZnzhRZoe4AbQixkioVCCMrf5CM5+Coo77bKqjWXCKSEaspkW/H9fIhQ3f2tlw0dBeLBobz9tXn53nPpD6K2iOk6RSLlApJAOfkdWBpMWuXAjIfj4mjaXL/LMLj5OkiMWdCaO4hTneJYOmzNNJ0glPBzS7jMRs7akPZleqgHo/vW1NAT+gh4sE5/M6GfSeEv0q84VfXYBrRMrQsnzkyBTfGz7KTJ5itAgGTplnPZwhLD1CcLAOEZEt1M5vwdj1IX1Db9jX4wx5KNaDk+RzseqjfchEM00qhGHxWPl1UnqthdVEbnWR+Bed25ULOtWxoVDzukARSF1a0N76vA9wqmEoHu4eoY8VIlkRdy615Iu1Lb+5ozEz7gQY7sOhZQ0hXSyyk+PEG8GvbmMJ6BaMP1Wz2XNy79GLi1oYTP6vRiRmL0ryGZswj9v8SgU/+9iULx0RuFqbpxHO72MtrlD4vagxc/119A4nBzJEu2oM=

cache:
  directories:
    - node_modules

env:
  global:
    secure: Yh93a5R4Gh93NyPGVF/jEMBUYvcxEWMqbHwXBpAG4frjlW2y79ttOo59jLF8jHd/Rd60TqlLNEixAJmlZ4eeHpdyJYOSofcT5V6aJgieSY0synVWAQ57Alyxp7IUqBKkmqQy8FAeW68OLb17DMUKzfxvXZ6aZmX1ClCyFiSX1IWqqCW+f61EWmr3exKoTVZtV/5HFeZQE8N1leU+XFwSYmx99jtm+Ii7kZgo3izbcEvn1WLc/0nH0hS2vj8iGJ/bwyvNClS7ilse2Lc3D3IfOaMpFupy3CVxmdAnDbpJYSUREVTuTGF7AK2Aij/a6/kcS9GwhvEf8dJtnKi57IasAV8vMhgpvqxWeApm9nu9WNRCS24qFDqPeewcB9we1MWm2DR3CHvIWUUPH8fRvSkyGAkeG7W7xpQAq6iG6QaA5RWcME5e/iCj9YGkySABqnvBuuWZM+92rpRPD5RaPdab8Xsu33TKwf69rwN0FHGWCC757E3GxkSHXYmniHHVdoqQyE5BT8QErsrXcS0yFqb6s2zRRfyk5ZGWMMjY15telwfGhj30Oj0p/66UhxsSoVxf7m1yv6628l4oDi5bXAVYg06RTIij9uEo+bFxjfXmPmrhbMKHuFLSx2LR+tj4RC6fzG4Jas/6nZ+dPqdke2TH/Yvc1LBKkKsoZiAbNHDgHrw=

install: 'npm install'
before_script: 'snyk auth $SNYK_TOKEN'
script: 'npm test'
