language: node_js
node_js:
  - '7'
  - '6'

notifications:
  email:
    on_success: never
    on_failure: change

cache:
  yarn: true
  directories:
    - node_modules

env:
  global:
    secure: i4tk4jIv2LmHxgD1dyfG3PDexvHRyjd7F17OCRg4831XRKsjsW2fuP5P9UcFf2OnARUrDc8tdQ8EBPF7RUAPYENNUMrirMyHE4iGfnXTj2l1EvIv9AZRswnd/ExkgUyJmBx6d1O/hxq2e+aqjAHjRradbjuottFAOBMTdAtUeDh+4lOQAzsWiWBWefuEEtujKxt1RQ7sox40v0hl6Ck83Zq6EEkWlkdYYKz7GHUjbj+O10YL8xPkwMLVe9jIT1aLifi012tWF3hCckgqqY/HRPAdgpC+CiYUI61zkC3N/zFHrkDkozvJw9hg64SOIMm5cbTOeDCiiOzgzrstwQFjmeb3v8ZraUYDsyaULrqlvuPSAbklleqIxgci+fwiynNSTZKlow6A54fVG91CXyHJXxGvhRtAReFBNxPOZhUkxjbdW1b9HE/IZdgmVmsuLD3dSvY0OxJvf1OVXC/Wr0vR+Q5kMr2l0RVoIeho94G7pQF8fAMWFHPZcRDfvpqSYiv0O1a0BU/tZaVWcbQPV1WuXHyeCbFzKAlnWHZphoUop4xITpudhZZIKjmidHbl+15AHKckxUP2UFXuN58vTBqCudLgKroS41BxgtwgrdGaimFuWY7ZUnSfCXIlRArUjok49fEdkYDg4yX/VIwxxUzjiQynIEn328zxAeKmm1xf2B0=

before_script: 'snyk auth $SNYK_TOKEN'
script: 'yarn test'
after_script: 'curl -s https://raw.githubusercontent.com/atom/ci/master/build-package.sh | sh'
